version: '3.7'

x-common: &common
  volumes:
    - "${PWD}:/opt/php-version-audit"
  working_dir: /opt/php-version-audit

services:
  composer:
    <<: *common
    image: composer:2.0
    volumes:
    - "${PWD}:/opt/php-version-audit"
    - "${HOME}/.composer:/tmp"

  php:
    <<: *common
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    environment:
      REQUIRE_VERSION_ARG: ${REQUIRE_VERSION_ARG:-false}

  phpstan:
    <<: *common
    image: ghcr.io/phpstan/phpstan:1
    command: analyse ./src

  alpine:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.alpine
    image: lightswitch05/php-version-audit:alpine

  buster:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.buster
    image: lightswitch05/php-version-audit:buster
